### PR TITLE
Add support for general api token

### PR DESCRIPTION
**Pull request by mjtice**

### CODE REVIEW

**Comment by floatingstatic** [comment]
Hi @mjtice thanks for the contribution. This looks pretty good. I loaded this in my st2-docker test environment and ran some quick tests. All of the actions work beautifully with the new auth method however we also need to update the sensor code in your branch. Somewhere around here:

https://github.com/mjtice/stackstorm-jira/blob/a36af44c6b0c5d9ae37d228aec4110cae47f1daf/sensors/jira_sensor_for_apiv2.py#L59-L63

Otherwise we get an exception when the sensor starts as it is unaware of the new `api_token` auth method.

```
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-]   File "/opt/stackstorm/packs/jira/sensors/jira_sensor.py", line 67, in setup
st2sensorcontainer_1   |
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-]
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-] raise Exception(msg)
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-]
st2sensorcontainer_1   |
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-] Exception
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-] :
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-] ('You must set auth_method to either "oauth"', 'or "basic" your jira.yaml config file.')
st2sensorcontainer_1   | 2023-07-07 01:36:45,908 ERROR [-]
st2sensorcontainer_1   |
```

If you wouldn't mind fixing that up, I see no issues merging this. Thanks again!

**Comment by floatingstatic** [comment]
Sorry one other small detail you will want to update this in `sensors/jira_sensor_for_apiv2.py` as well as `sensors/jira_sensor.py` but the change is basically the same in both files. Thanks!

**Comment by mjtice** [comment]
I added the api_token auth method into the sensors.  They were also missing 'pat' and 'cookie' so I added them, too.

**Review by floatingstatic — APPROVED** [review]
Looks good to me. Sensor is now working in my test env. Thanks for adding the missing auth methods in the sensor as well, much appreciated.

**Pull request merged**
