### PR TITLE
Update the Jira module

### LINKED ISSUE #48: Unable to assign issue
I am getting the error `'accountId' must be the only user identifying query parameter in GDPR strict mode.`, which per Jira's docs was resulting of an [API change in 2019](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).  To fix this issue the package should be updated and tested ([to the current pip version](https://pypi.org/project/jira/)).

### PR DESCRIPTION
**Pull request by mamercad**
Update the Jira module to `3.2.0` and freshen up the `README.md`; fixes #48.

```shell
❯ st2 pack install 'https://github.com/mamercad/stackstorm-jira.git=update'

	[ succeeded ] init_task
	[ succeeded ] download_pack
	[ succeeded ] make_a_prerun
	[ succeeded ] get_pack_dependencies
	[ succeeded ] check_dependency_and_conflict_list
	[ succeeded ] install_pack_requirements
	[ succeeded ] get_pack_warnings
	[ succeeded ] register_pack

+-------------+-------------------+
| Property    | Value             |
+-------------+-------------------+
| ref         | jira              |
| name        | jira              |
| description | Jira integrations |
| version     | 1.1.0             |
| author      | StackStorm, Inc.  |
+-------------+-------------------+
```

```shell
❯ st2 run jira.create_issue summary="Hello, StackStorm"
.
id: 639e0462339d9bb322da4181
action.ref: jira.create_issue
context.user: mark
parameters:
  summary: Hello, StackStorm
status: succeeded
start_timestamp: Sat, 17 Dec 2022 18:03:14 UTC
end_timestamp: Sat, 17 Dec 2022 18:03:16 UTC
result:
  exit_code: 0
  result:
    assignee: null
    created_at: 2022-12-17T13:03:15.413-0500
    description: null
    id: '10010'
    key: HOME-11
    labels: []
    reporter: Mark Mercado
    resolution: null
    resolved_at: null
    status: To Do
    summary: Hello, StackStorm
    updated_at: 2022-12-17T13:03:15.413-0500
    url: https://redacted.atlassian.net/browse/BUGS-11
  stderr: ''
  stdout: ''
```

### CODE REVIEW

**Review by arm4b — APPROVED** [review]
Thanks for the refresh!

**Comment by arm4b** [comment]
Looks like the CI is failing for this change.

Per https://pypi.org/project/jira/ it Requires: Python >=3.8, while the CI runs python 3.6. That's why the CI fails for this PR.
https://github.com/StackStorm-Exchange/stackstorm-jira/actions/runs/3721226679/jobs/6311286519#step:5:1450

I'm not sure if we have an easy way for resolving this
```
  Installing pack requirements from requirements.txt
  ERROR: Could not find a version that satisfies the requirement jira==3.4.1
  ERROR: No matching distribution found for jira==3.4.1
```

**Comment by mamercad** [comment]
> Looks like the CI is failing for this change.
> 
> Per https://pypi.org/project/jira/ it Requires: Python >=3.8, while the CI runs python 3.6. That's why the CI fails for this PR. https://github.com/StackStorm-Exchange/stackstorm-jira/actions/runs/3721226679/jobs/6311286519#step:5:1450
> 
> I'm not sure if we have an easy way for resolving this
> 
> ```
>   Installing pack requirements from requirements.txt
>   ERROR: Could not find a version that satisfies the requirement jira==3.4.1
>   ERROR: No matching distribution found for jira==3.4.1
> ```

Yeah, hrm, Python 3.6 has been EoL for a while -- what's the story around Python versions and StackStorm packs, in general?

**Comment by arm4b** [comment]
We need to support both 3.6 and 3.8 so far and so the paks should ideally work with those.

The reason is that with the current OS matrix we support (EL7, EL8, U18, U20), one of those OSes is still on py3.6 (I think U18?).
We want to deprecate U18 when the EOL time comes early next year and replace it with U22 (which comes with the py3.10 we need to add support for too).

BTW it was a topic for discussion in the last TSC meeting (https://github.com/StackStorm/community/issues/114) and likely will be a difficulty to solve for the next release. So the Python version matrix is something we should keep in mind.

**Comment by mamercad** [comment]
> We need to support both 3.6 and 3.8 so far and so the paks should ideally work with those.
> 
> The reason is that with the current OS matrix we support (EL7, EL8, U18, U20), one of those OSes is still on py3.6 (I think U18?). We want to deprecate U18 when the EOL time comes early next year and replace it with U22 (which comes with the py3.10 we need to add support for too).
> 
> BTW it was a topic for discussion in the last TSC meeting ([StackStorm/community#114](https://github.com/StackStorm/community/issues/114)) and likely will be a difficulty to solve for the next release. So the Python version matrix is something we should keep in mind.

Yeah, makes sense ... I maintain Ansible things, so, I'm aware of this pain 😄

**Comment by mamercad** [comment]
> > We need to support both 3.6 and 3.8 so far and so the paks should ideally work with those.
> > The reason is that with the current OS matrix we support (EL7, EL8, U18, U20), one of those OSes is still on py3.6 (I think U18?). We want to deprecate U18 when the EOL time comes early next year and replace it with U22 (which comes with the py3.10 we need to add support for too).
> > BTW it was a topic for discussion in the last TSC meeting ([StackStorm/community#114](https://github.com/StackStorm/community/issues/114)) and likely will be a difficulty to solve for the next release. So the Python version matrix is something we should keep in mind.
> 
> Yeah, makes sense ... I maintain Ansible things, so, I'm aware of this pain 😄

We should get 3.8 and 3.10 added to the pack build and test matrix, eh?

**Comment by arm4b** [comment]
Definitely would be nice adding py3.8 to the packs build matrix as that's de-facto supported by StackStorm (https://github.com/StackStorm/st2/blob/9d0be4e2c3a906c3eab75164e1664f15ab2efb69/.github/workflows/ci.yaml#L153-L176)

For py3.10, we need to ensure the StackStorm core could be built with that version first:
@amanda11 tried first experiments with it here: https://github.com/StackStorm/st2/pull/5843

**Comment by mamercad** [comment]
> Definitely would be nice adding py3.8 to the packs build matrix as that's de-facto supported by StackStorm (https://github.com/StackStorm/st2/blob/9d0be4e2c3a906c3eab75164e1664f15ab2efb69/.github/workflows/ci.yaml#L153-L176)
> 
> For py3.10, we need to ensure the StackStorm core could be built with that version first: @amanda11 tried first experiments with it here: [StackStorm/st2#5843](https://github.com/StackStorm/st2/pull/5843)

I opened a Draft PR if you want to have the conversation there...

**Comment by amanda11** [comment]
> Definitely would be nice adding py3.8 to the packs build matrix as that's de-facto supported by StackStorm (https://github.com/StackStorm/st2/blob/9d0be4e2c3a906c3eab75164e1664f15ab2efb69/.github/workflows/ci.yaml#L153-L176)
> 
> 
> 
> For py3.10, we need to ensure the StackStorm core could be built with that version first:
> 
> @amanda11 tried first experiments with it here: https://github.com/StackStorm/st2/pull/5843
> 
> 

We also need to support python 3.9 as RHEL drop support on El8 for python 3.8 next year - but will support python 3.9.
From my experiments that is an easier upgrade to support - I also have a pr in draft for that. Only issue is pylons test failure.

**Comment by mamercad** [comment]
@armab What are we doing about this, waiting for Python 3.6 to age out?

**Comment by arm4b** [comment]
Is there a version of the Jira pack that works with both py3.6 and py3.8? 
That would be the ideal path here. We definitely can't merge this with failed py3.6 tests.

Otherwise, let's try https://peps.python.org/pep-0508/#environment-markers to specify different Jira versions depending on the python version.

**Comment by mamercad** [comment]
> Is there a version of the Jira pack that works with both py3.6 and py3.8? That would be the ideal path here. We definitely can't merge this with failed py3.6 tests.
> 
> Otherwise, let's try https://peps.python.org/pep-0508/#environment-markers to specify different Jira versions depending on the python version.

Looks like the last version to support Python 3.6 is [3.2.0](https://github.com/pycontribs/jira/releases/tag/3.2.0).

**Review by arm4b — APPROVED** [review]
Nice! Thanks.

**Comment by amanda11** [comment]
> @armab What are we doing about this, waiting for Python 3.6 to age out

At moment investigating how much work involved in supporting python 3.9 and 3.10. 3.9 looks like just one issue with astroid/pylint, 3.10 - quite a lot!

**Pull request merged**
